name: customer_usage_bill
jobs:
  - destination_dataset: curated
    destination_table: customer_usage_bill
    write_disposition: WRITE_TRUNCATE
    query: >
      SELECT 
          c.customer_id,
          c.city,
          CASE 
              WHEN csu.usage_id IS NOT NULL THEN 'Cellular'
              WHEN hiu.usage_id IS NOT NULL THEN 'Home Internet'
              ELSE 'No Usage'
          END AS usage_type, -- Indicates Cellular or Home Internet
          COALESCE(SUM(csu.usage_amount), SUM(hiu.data_usage_amount), 0) AS total_usage_amount, -- Sum usage amounts
          b.plan_type, -- Plan type from Billing
          b.billing_amount -- Billing amount
      FROM 
          `bellassignment-453021.expl.customers` c
      LEFT JOIN 
          `bellassignment-453021.expl.billing` b
      ON 
          c.customer_id = b.customer_id
      LEFT JOIN 
          `bellassignment-453021.expl.cellular_service_usage` csu
      ON 
          c.customer_id = csu.customer_id
      LEFT JOIN 
          `bellassignment-453021.expl.home_internet_usage` hiu
      ON 
          c.customer_id = hiu.customer_id
      GROUP BY 
          c.customer_id, c.city, usage_type, b.plan_type, b.billing_amount
      ORDER BY 
          c.customer_id;
