name: customer_usages
jobs:
  - destination_dataset: curated
    destination_table: customer_usage_bill
    write_disposition: WRITE_TRUNCATE
    query: >
      SELECT 
          c.customer_id,
          c.state_province AS province,
          CASE 
              WHEN csu.usage_id IS NOT NULL THEN 'Cellular'
              WHEN hiu.usage_id IS NOT NULL THEN 'Home Internet'
              ELSE 'No Usage'
          END AS usage_type,
          COALESCE(SUM(csu.usage_amount), SUM(hiu.data_usage_amount), 0) AS total_usage_amount,
          b.plan_type,
          b.billing_amount
      FROM 
          `bellassignment-453021.expl.customers` c
      LEFT JOIN 
          `bellassignment-453021.expl.billing` b
      ON 
          c.customer_id = b.customer_id
      LEFT JOIN 
          `bellassignment-453021.expl.cellular_service_usage` csu
      ON 
          c.customer_id = csu.customer_id
      LEFT JOIN 
          `bellassignment-453021.expl.home_internet_usage` hiu
      ON 
          c.customer_id = hiu.customer_id
      GROUP BY 
          c.customer_id, c.state_province, usage_type, b.plan_type, b.billing_amount
      ORDER BY 
          c.customer_id;

  - destination_dataset: curated
    destination_table: internet_customer_prov_count
    write_disposition: WRITE_TRUNCATE
    query: >
      SELECT 
          c.state_province AS province,
          COUNT(DISTINCT c.customer_id) AS customer_count,
          AVG(b.billing_amount) AS average_bill_amount
      FROM 
          `bellassignment-453021.expl.customers` c
      JOIN 
          `bellassignment-453021.expl.home_internet_usage` hiu
      ON 
          c.customer_id = hiu.customer_id
      JOIN 
          `bellassignment-453021.expl.billing` b
      ON 
          c.customer_id = b.customer_id
      GROUP BY 
          c.state_province
      ORDER BY 
          customer_count DESC;

  - destination_dataset: curated
    destination_table: cellular_customer_prov_count
    write_disposition: WRITE_TRUNCATE
    query: >
      SELECT 
          c.state_province AS province,
          COUNT(DISTINCT c.customer_id) AS customer_count,
          AVG(b.billing_amount) AS average_bill_amount
      FROM 
          `bellassignment-453021.expl.customers` c
      JOIN 
          `bellassignment-453021.expl.cellular_service_usage` csu
      ON 
          c.customer_id = csu.customer_id
      JOIN 
          `bellassignment-453021.expl.billing` b
      ON 
          c.customer_id = b.customer_id
      GROUP BY 
          c.state_province
      ORDER BY 
          customer_count DESC;
